export const VEHICLE_BRAND = {
  POR_DEFECTO: 'Por Defecto',
  AUDI: 'Audi',
  BMW: 'BMW',
  CITROEN: 'Citroën',
  FIAT: 'Fiat',
  FORD: 'Ford',
  HONDA: 'Honda',
  HYUNDAI: 'Hyundai',
  JAGUAR: 'Jaguar',
  JEEP: 'Jeep',
  KIA: 'Kia',
  LAND_ROVER: 'Land Rover',
  LEXUS: 'Lexus',
  MAZDA: 'Mazda',
  MERCEDES_BENZ: 'Mercedes Benz',
  MINI: 'Mini',
  NISSAN: 'Nissan',
  OPEL: 'Opel',
  PEUGEOT: 'Peugeot',
  RANGE_ROVER: 'Range Rover',
  RENAULT: 'Renault',
  SEAT: 'Seat',
  SKODA: 'Skoda',
  TESLA: 'Tesla',
  TOYOTA: 'Toyota',
  VOLKSWAGEN: 'Volkswagen',
}